const header = document.getElementById('siteHeader'); const menuToggle = document.getElementById('menuToggle'); const navMenu = document.getElementById('navMenu'); const navLinks = [...document.querySelectorAll('.nav-link')]; const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function setHeader() { header.classList.toggle('scrolled', window.scrollY > 24) } setHeader(); window.addEventListener('scroll', setHeader, { passive: true });
menuToggle.addEventListener('click', () => { const open = navMenu.classList.toggle('open'); menuToggle.classList.toggle('open', open); menuToggle.setAttribute('aria-expanded', open) }); navMenu.addEventListener('click', e => { if (e.target.matches('a')) { navMenu.classList.remove('open'); menuToggle.classList.remove('open'); menuToggle.setAttribute('aria-expanded', 'false') } });
document.querySelectorAll('a[href^="#"]').forEach(a => a.addEventListener('click', e => { const id = a.getAttribute('href'); const target = document.querySelector(id); if (target) { e.preventDefault(); target.scrollIntoView({ behavior: reduced ? 'auto' : 'smooth' }); history.replaceState(null, '', id) } }));
const revealObserver = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); revealObserver.unobserve(entry.target) } }) }, { threshold: .02, rootMargin: '0px 0px -10px 0px' }); document.querySelectorAll('.reveal').forEach(el => revealObserver.observe(el));
const counters = document.querySelectorAll('.counter'); let countersDone = false; const counterObserver = new IntersectionObserver(entries => { if (countersDone) return; entries.forEach(entry => { if (entry.isIntersecting) { countersDone = true; counters.forEach(counter => { const target = Number(counter.dataset.target); if (reduced) { counter.textContent = target; return } let current = 0; const step = Math.max(1, Math.ceil(target / 60)); const timer = setInterval(() => { current += step; if (current >= target) { current = target; clearInterval(timer) } counter.textContent = current }, 24) }) } }) }, { threshold: .5 }); if (counters[0]) counterObserver.observe(counters[0]);
const sections = [...document.querySelectorAll('main section[id]')]; const activeObserver = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) { navLinks.forEach(link => link.classList.toggle('active', link.getAttribute('href') === `#${entry.target.id}`)) } }) }, { threshold: .45 }); sections.forEach(section => activeObserver.observe(section));
const filterButtons = document.querySelectorAll('.filter'); const projectCards = document.querySelectorAll('.project-card'); filterButtons.forEach(button => button.addEventListener('click', () => { filterButtons.forEach(btn => btn.classList.remove('active')); button.classList.add('active'); const filter = button.dataset.filter; projectCards.forEach(card => { const show = filter === 'all' || card.dataset.category === filter; card.style.display = 'block'; requestAnimationFrame(() => card.classList.toggle('hide', !show)); if (!show) setTimeout(() => { if (card.classList.contains('hide')) card.style.display = 'none' }, 320) }) }));
const testimonials = [...document.querySelectorAll('.testimonial')]; const prev = document.querySelector('.prev'); const next = document.querySelector('.next'); let currentTestimonial = 0; function showTestimonial(index) { testimonials[currentTestimonial].classList.remove('active'); currentTestimonial = (index + testimonials.length) % testimonials.length; testimonials[currentTestimonial].classList.add('active') } prev.addEventListener('click', () => showTestimonial(currentTestimonial - 1)); next.addEventListener('click', () => showTestimonial(currentTestimonial + 1)); if (!reduced) setInterval(() => showTestimonial(currentTestimonial + 1), 6500);
const parallax = document.querySelector('.parallax img'); function moveParallax() { if (!parallax || reduced) return; const rect = parallax.parentElement.getBoundingClientRect(); const offset = rect.top * -.08; parallax.style.transform = `translate3d(0,${offset}px,0)` } window.addEventListener('scroll', moveParallax, { passive: true }); moveParallax();
const form = document.getElementById('contactForm'); const status = document.getElementById('formStatus'); if (form && status) { form.addEventListener('submit', e => { e.preventDefault(); let valid = true; status.textContent = ''; status.className = 'form-status'; form.querySelectorAll('.field').forEach(field => { const input = field.querySelector('input,select,textarea'); const bad = !input.checkValidity() || !String(input.value).trim(); field.classList.toggle('error', bad); if (bad) valid = false }); const email = form.email.value.trim(); if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) { form.email.closest('.field').classList.add('error'); valid = false } if (!valid) { status.textContent = 'Please complete the highlighted fields with valid information.'; status.classList.add('error'); return } status.textContent = 'Thank you. Your estimate request has been received. Our team will contact you shortly.'; status.classList.add('success'); form.reset() }); form.addEventListener('input', e => { const field = e.target.closest('.field'); if (field) field.classList.remove('error') }); }
